---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  build:
    name: build
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t juice-shop:${{github.sha}}
