name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build image
          run: |
            docker build -t juice-shop:${{github.sha}} .
        - name: Grype Scan
          uses: anchore/scan-action@v3
          with:
              image: "juice-shop:${{github.sha}}"
              fail-build: false
        - name: Generate SBOM
          uses: anchore/sbom-action@v0
          with:
              image: "juice-shop:${{github.sha}}"
  Sast-scan:
        name: semgrep
        runs-on: ubuntu-20.04
        container: returntocorp/semgrep
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Semgrep
            run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true
          - name: Upload Sarif file
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: 'semgrep.sarif'

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        
        
              
       
            
          
      
  
  
